### ISSUE TITLE
Getting error in Creation of a Secret

### ISSUE THREAD

**Issue by navneetccna** [plmary/SecretManager#11]
When Use SecretServer = Yes

Erreur sur serveur "Ajax_secrets.js" - "CTRL_SRV_X" : <br />
<b>Notice</b>:  Undefined variable: Connection refused in <b>/var/www/SecretManager/SM-secrets.php</b> on line <b>2176</b><br />
{"Status":"error","Message":null}

When Use SecretServer = No

SecretManager files integrity Alert

(./SM-users.php
./SM-preferences.php
./SM-admin.php
./SM-login.php
./SM-home.php
./SM-control.php
./SM-secrets.php)

**Comment by plmary** [comment]
Sorry for this wait. The new version fixe your problem. Could you retry ?
